### ISSUE TITLE
Question / Request: Is it possible to bind to a pseudo-selector style?

### ISSUE THREAD

**Issue by xtagon** [andrewtimberlake/ember-style-bindings#1]
Hi,

First, thank you for making this library, it's very useful!

Is there a way to apply styles to a component that apply to pseudo-selectors such as `:before`?

Here is my use case, I have an image display style that has to dynamically add padding-top values to a `:before` pseudo-selector in order to offset some absolute positioning and other tricky CSS values. I have it working right now, but it requires that I add it to a `<style>` tag in the htmlbars template, like this:

```
{{#if aspectRatioPadding}}
  <style>
    #{{elementId}}:before {
      content: "";
      display: block;
      {{css-properties padding-top=aspectRatioPadding}}
    }
  </style>
{{/if}}
```

Is it possible to do it with this library in the component, without using css-properties and putting it in the template like this? I think it would be cleaner.

Thanks,

Justin

**Comment by andrewtimberlake** [comment]
> The style attribute only defines style properties for a given HTML element. Pseudo-classes and pseudo-elements the are a member of the family of selectors, which don't occur in the attribute so you cant style them inline.

This component simply generates a `style` attribute for the element of a component using the bound properties. Pseudo-selectors refer to a different element and so are outside of the scope of this component.
