### ISSUE TITLE
Null or undefined values result in invalid CSS properties

### ISSUE THREAD

**Issue by xtagon** [andrewtimberlake/ember-style-bindings#2]
Hi,

I noticed an issue where sometimes I want the value of a bound style to be a null or unset instead of a value. Of course I can set it to something like `inherit` or `none` or `unset` depending on the CSS property but sometimes there's no easy way to avoid overriding behavior when you just want it to not change the property in that case.

I tried passing `null`, but for some properties this seems to set CSS like: `width: px;` (where there is an empty space before `px`) and I tried `undefined` which technically works, but produces `width: ;` (without the `px`).

I'd like to just exclude the style if the computed property is `null` or `undefined`.

Would you accept a PR for this?

**Comment by andrewtimberlake** [comment]
Sure, a PR would be great.

**Comment by xtagon** [comment]
Great, I'll see what I can do.
